// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfig(arg1) {
  return window['go']['main']['App']['AddConfig'](arg1);
}

export function ChangeDefault(arg1) {
  return window['go']['main']['App']['ChangeDefault'](arg1);
}

export function CheckSk(arg1) {
  return window['go']['main']['App']['CheckSk'](arg1);
}

export function DoOcr(arg1) {
  return window['go']['main']['App']['DoOcr'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigCount() {
  return window['go']['main']['App']['GetConfigCount']();
}

export function GetFields() {
  return window['go']['main']['App']['GetFields']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RemoveConfig(arg1) {
  return window['go']['main']['App']['RemoveConfig'](arg1);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function UpdateFields(arg1) {
  return window['go']['main']['App']['UpdateFields'](arg1);
}
